# Generated by Django 5.1.1 on 2024-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0005_listing_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("RD", "Records"),
                    ("CL", "Clothing"),
                    ("PS", "Posters"),
                    ("MS", "Miscellanous"),
                ],
                max_length=5,
            ),
        ),
    ]
