# Generated by Django 5.1.1 on 2024-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0007_remove_listing_like_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="mandro",
            field=models.TextField(default=False),
        ),
    ]
